name: Workflow Linting
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .github/workflows/*
      - .ci/tools/go.mod
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version
      - name: Install actionlint
        run: cd .ci/tools && go install github.com/rhysd/actionlint/cmd/actionlint
      - name: Run actionlint on workflow files
        run: actionlint -shellcheck=
